on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: CI

jobs:

  jekyll-build:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jekyll-version: [3.9, 4.3]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Not needed with a .ruby-version file
        bundler-cache: false
    - name: Bundle Install
      run: bundle install
    - name: Install Jekyll ${{ matrix.jekyll-version }}
      run: gem install jekyll -v ${{ matrix.jekyll-version }}
    - name: Init Search
      run: bundle exec rake search:init
    - name: Build Site
      run: bundle exec jekyll build

  assets:
    name: Test CSS and JS
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm test
